### ISSUE TITLE
Document that building against 2.7 requires default-features = false

### ISSUE THREAD

**Issue by ilianaw** [ilianaw/rust-crowbar#17]
Since https://github.com/ilianaw/rust-crowbar/commit/3d02dec679b8413f4c09ddcebdf8d02df3e4bd00, building for Python 2.7 requires this incantation in your Cargo.toml:

```toml
[dependencies]
crowbar = { version = "0.2", default-features = false }
cpython = { version = "0.1", default-features = false }

[features]
default = ["cpython/python27-sys"]
```

This is awkward but we might be able to gently push people onto Python 3.6 instead by documenting this pitfall. :)
